# The 'version' attribute is removed from the top.

services:
  alzheimer-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alzheimer_detector
    # This is CRITICAL. It gives the container access to host devices like the Edge TPU.
    privileged: true
    volumes:
      # Mount the host's USB devices so the container can find the Edge TPU.
      - /dev/bus/usb:/dev/bus/usb
      # Mount the model directory as read-only into the container's working directory.
      - ./model:/app/model:ro
      # Mount the test images directory as read-only.
      - ./test:/app/test:ro
    # The ENTRYPOINT in the Dockerfile is "/app/alzheimer".
    # This command passes arguments to it. The path is relative to the WORKDIR (/app).
    # You can change "test/1(10).png" to any other image in your ./test folder.
    command: ["-f", "test/1(10).png"]